trigger:
  - main  # Runs pipeline on push to main branch

pool:
  name: Default  # Self-hosted agent pool

stages:
  - stage: Setup
    displayName: 'Install Required Dependencies'
    jobs:
      - job: InstallDocker
        displayName: 'Docker Installation'
        steps:
         - task: DockerInstaller@0
           inputs:
             dockerVersion: '17.09.0-ce'

  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image to ACR'
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push Docker Image to ACR'
        steps:
        - task: Docker@2
          inputs:
              containerRegistry: 'acrTest'
              repository: 'web-game'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/web-app/Dockerfile'
              tags: 'latest'
        - task: Docker@2
          inputs:
              containerRegistry: 'acrTest'
              repository: 'web-game'
              command: 'push'
              Dockerfile: '$(Build.SourcesDirectory)/web-app/Dockerfile'
              tags: 'latest'

  - stage: Deploy
    displayName: 'Deploy to AKS'
    jobs:
      - job: Deploy
        displayName: 'Deploy to AKS'
        steps:
          - task: CmdLine@2
            inputs:
              script: cat 01_kubernetes_aks/app-deploy.yaml
            displayName: 'Display Kubernetes Deployment File'

          - task: KubernetesManifest@1
            inputs:
              action: 'createSecret'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'aksTest'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: 'myscecret'
              dockerRegistryEndpoint: 'acrTest'

          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'aksTest'
              namespace: 'default'
              manifests: '01_kubernetes_aks/app-deploy.yaml'
            
