apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-game
spec:
  progressDeadlineSeconds: 1200
  replicas: 1
  selector:
    matchLabels:
      app: web-game
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web-game
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web-game
        image: acrlab008.azurecr.io/web-game:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: web-game
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-game